bot:
  name: OOO_Aisberg_bot
  token: 6180998842:AAFuB1ON6E5x_dgB-GLrvN3fk8rRQoyzP7Q
  chatId: id_1

botcommands:
  commands:
    start: "start bot"
    help: "help bot"
    update: "update bot"
    hello: "hello bot"
    bye: "bye bot"
    goode: "goode bot"
